### ISSUE TITLE
URL dest

### ISSUE THREAD

**Issue by doowb** [helpers/helper-apidocs#2]
I was able to get `verb` updated to `0.4.5` in `assemble 0.6.0` and saw the `{%= apidocs(resolve(...)) %}` tags in some of the api docs files. After adding `resolve` as a dependency and adding `verb.helper('resolve', require('resolve').sync);` to the `verbfile.js`, it worked!!!

The only issue is that I noticed you had the docs building with references to the file on github when dest is a URL. This isn't working in the version of `apidocs` with `verb 0.4.5` so I'm thinking you might have a different local version that does this awesomeness :wink:

**Comment by jonschlinkert** [comment]
lol thanks. I pushed up a new version of js-comments. I think it should work now.
