### ISSUE TITLE
in v0.5.0, dropped support for `patterns` to be array?

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-apidocs#5]
it's not so big damage, but just asking, cuz i'm not sure.

Just because I'm updating [apidocs-cli](https://github.com/tunnckoCore/apidocs-cli)

**Comment by jonschlinkert** [comment]
not intentionally, but there are all kinds of things I want to do differently about this.

**Comment by tunnckoCore** [comment]
haha, oookey. i've just work around it already.
